#ifndef _TILESET
#define _TILESET

typedef enum {
	TITLE, SELECT_LEVEL, SELECT_LEVEL_BG, BUTTON, PAUSE, PAUSE_BUTTON, STATUE, DUCK_INTRO, CONGRATULATIONS, GAME_COMPLETE, END_BUTTON, HAT_DUCK,
	T_GROUND,
	T_SPIKE_UP, T_SPIKE_RIGHT, T_SPIKE_DOWN, T_SPIKE_LEFT,
	T_EGG_UP, T_EGG_DOWN, T_EGG_RIGHT, T_EGG_LEFT, EGG_CAUGHT,
	DUCK_UP_RIGHT, DUCK_UP_LEFT, DUCK_DOWN_RIGHT, DUCK_DOWN_LEFT, DUCK_RIGHT_UP, DUCK_RIGHT_DOWN, DUCK_LEFT_UP, DUCK_LEFT_DOWN,
	GROWING_DUCK_UP_RIGHT, GROWING_DUCK_UP_LEFT, GROWING_DUCK_DOWN_RIGHT, GROWING_DUCK_DOWN_LEFT, GROWING_DUCK_RIGHT_UP, GROWING_DUCK_RIGHT_DOWN, GROWING_DUCK_LEFT_UP, GROWING_DUCK_LEFT_DOWN,
	T_GRAVITY_SWITCH,
	T_CUBE,
	CATERPILLAR_UP_RIGHT, CATERPILLAR_UP_LEFT, CATERPILLAR_DOWN_RIGHT, CATERPILLAR_DOWN_LEFT, CATERPILLAR_RIGHT_UP, CATERPILLAR_RIGHT_DOWN, CATERPILLAR_LEFT_UP, CATERPILLAR_LEFT_DOWN,
	T_PLANT_RIGHT, T_PLANT_LEFT,
	T_BEE_RIGHT, T_BEE_LEFT, BEE_HALO,
	T_BULLET,
	T_PESTLE_UP, T_PESTLE_DOWN, T_PESTLE_RIGHT, T_PESTLE_LEFT,
	BIG_BLAST, SMALL_BLAST
} Tileset_name;

typedef struct {
	int width, height, length;
	char** tile;
	int tiles_in_rom;
	const short* palette;
} Tileset;

Tileset* tileset_load (Tileset_name name);
void tileset_free(Tileset* tileset);

#endif //_TILESET
